export { default as Logo } from './logo/Logo'
export { default as GameCard } from './game-card/GameCard'
export { default as Navbar } from './navbar/Navbar'
export { default as NavbarLogo } from './navbar-logo/NavbarLogo'
export { default as SearchBar } from './search-bar/SearchBar'
export { default as Filters } from './filters/Filters'
export { default as Pagination } from './pagination/Pagination'
export { default as Loader } from './loader/Loader'
export { default as ErrorHandler } from './error-handler/ErrorHandler'
// export { default as SearchIcon } from './icons/SearchIcon'
// export { default as PlusIcon } from './icons/PlusIcon'
// export { default as StarIcon } from './icons/StarIcon'
